# Generated by Django 5.1.2 on 2025-01-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SamlConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idp_entity_id', models.URLField(max_length=500, verbose_name='IdP Entity ID')),
                ('idp_sso_url', models.URLField(max_length=500, verbose_name='IdP Single Sign-On URL')),
                ('idp_slo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='IdP Single Logout URL')),
                ('idp_x509cert', models.TextField(blank=True, null=True, verbose_name='IdP x509 Certificate')),
                ('sp_entity_id', models.URLField(max_length=500, verbose_name='SP Entity ID')),
                ('sp_acs_url', models.URLField(max_length=500, verbose_name='SP Assertion Consumer Service (ACS) URL')),
                ('sp_slo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='SP Single Logout URL')),
                ('sp_x509cert', models.TextField(blank=True, null=True, verbose_name='SP x509 Certificate')),
                ('sp_private_key', models.TextField(blank=True, null=True, verbose_name='SP Private Key')),
                ('name_id_format', models.CharField(blank=True, default='urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress', max_length=255, verbose_name='NameID Format')),
                ('want_messages_signed', models.BooleanField(default=True)),
                ('want_assertions_signed', models.BooleanField(default=False)),
                ('authn_requests_signed', models.BooleanField(default=True)),
                ('logout_requests_signed', models.BooleanField(default=True)),
                ('logout_responses_signed', models.BooleanField(default=True)),
                ('signature_algorithm', models.CharField(default='http://www.w3.org/2001/04/xmldsig-more#rsa-sha256', max_length=255)),
                ('digest_algorithm', models.CharField(default='http://www.w3.org/2001/04/xmlenc#sha256', max_length=255)),
                ('strict', models.BooleanField(default=True)),
                ('debug', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False, help_text='Toggle to enable/disable SAML login.')),
            ],
        ),
    ]
