"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os

from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

from core.config import (
    ConfigurationError,
    parse_allowed_hosts,
    parse_bool,
    parse_csrf_trusted_origins,
    parse_samesite,
    require_secret,
)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

try:
    # Secrets are required in every environment. No source-controlled fallback is used.
    SECRET_KEY = require_secret('DJANGO_SECRET_KEY')
    ENCRYPTION_KEY = require_secret('DJANGO_ENCRYPTION_KEY')

    # DEBUG defaults to false so deployments cannot accidentally expose debug pages.
    DEBUG = parse_bool(os.environ.get('DJANGO_DEBUG'), default=False, name='DJANGO_DEBUG')

    ALLOWED_HOSTS = parse_allowed_hosts(os.environ.get('DJANGO_ALLOWED_HOSTS'))
    if not ALLOWED_HOSTS:
        if DEBUG:
            ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']
        else:
            raise ConfigurationError(
                'DJANGO_ALLOWED_HOSTS must be configured when DJANGO_DEBUG is false.'
            )

    # Only needed when a deployment's proxy/HTTPS topology makes the Origin/Referer
    # header not match DJANGO_ALLOWED_HOSTS on its own (see docs/deployment.md).
    # Empty by default: most deployments do not need this set.
    CSRF_TRUSTED_ORIGINS = parse_csrf_trusted_origins(os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS'))
except ConfigurationError as exc:
    raise ImproperlyConfigured(str(exc)) from exc



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cleanup.apps.CleanupConfig',
    'accounts',
    'saml_auth',
    'sso_auth',  # New unified SSO authentication app
    'integrator',  # Changed from 'sysbrix'
    'colorfield',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware', 
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
     'core.middleware.CompanyTimezoneMiddleware',
     'core.middleware.CompanySettingsMiddleware',
]
if not DEBUG:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')



ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'integrator.context_processors.company_logo_context', # Changed from 'sysbrix'
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # In production (or any time DATABASE_URL is set), parse it
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    # Fallback for local development: use SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# URLs for SAML redirection
LOGIN_URL = '/login/'  # Point LOGIN_URL to your standard login page
LOGOUT_URL = '/logout/' # Keep LOGOUT_URL as needed (or set to your standard logout)


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

#settings.py
DEFAULT_LOGO_TEXT = 'JHFRE'

COMPANY_CACHE_TIMEOUT = 60 * 60 * 24


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Production servers may serve public branding media from this root, but they
# MUST deny direct access to /media/uploads/.  Submitted files are protected
# records and must only be served by FileUploadDownloadView after authorization.

# Dynamic form uploads are validated again in SubmitFormView.  These hard caps
# bound every form, while a form's trusted configuration may set stricter
# limits.
DYNAMIC_UPLOAD_MAX_FILE_SIZE = 10 * 1024 * 1024
DYNAMIC_UPLOAD_MAX_TOTAL_SIZE = 25 * 1024 * 1024
DYNAMIC_UPLOAD_MAX_FILE_COUNT = 5
DYNAMIC_UPLOAD_MAX_IMAGE_PIXELS = 20_000_000
DYNAMIC_UPLOAD_ALLOWED_EXTENSIONS = {
    '.pdf', '.txt', '.csv',
    '.doc', '.docx', '.xls', '.xlsx', '.ppt', '.pptx',
    '.jpg', '.jpeg', '.png', '.gif', '.webp',
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security defaults that do not depend on reverse-proxy topology.
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'SAMEORIGIN'
SECURE_REFERRER_POLICY = 'same-origin'
SESSION_COOKIE_HTTPONLY = True

# Session cookie SameSite/Secure are deployment-specific: a cross-site SAML
# ACS POST (IdP -> browser -> Django) requires SameSite=None with Secure=true
# over HTTPS, while plain local HTTP development needs SameSite=Lax with
# Secure=false. Neither can be derived from DEBUG alone, since DEBUG=true can
# still run behind HTTPS during tunnel/testing deployments.
try:
    SESSION_COOKIE_SAMESITE = parse_samesite(
        os.environ.get('DJANGO_SESSION_COOKIE_SAMESITE'),
        default='Lax',
        name='DJANGO_SESSION_COOKIE_SAMESITE',
    )
    SESSION_COOKIE_SECURE = parse_bool(
        os.environ.get('DJANGO_SESSION_COOKIE_SECURE'),
        default=False,
        name='DJANGO_SESSION_COOKIE_SECURE',
    )
    if SESSION_COOKIE_SAMESITE == 'None' and not SESSION_COOKIE_SECURE:
        raise ConfigurationError(
            'DJANGO_SESSION_COOKIE_SAMESITE=None requires DJANGO_SESSION_COOKIE_SECURE=true; '
            'browsers reject SameSite=None cookies that are not marked Secure.'
        )
except ConfigurationError as exc:
    raise ImproperlyConfigured(str(exc)) from exc

CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = True #not DEBUG

# HTTPS redirects, forwarded-protocol trust, and HSTS require deployment
# knowledge.  They are opt-in, explicit production settings rather than an
# assumption that every deployment sits behind a compatible reverse proxy.
_secure_ssl_redirect_value = os.environ.get(
    'DJANGO_SECURE_SSL_REDIRECT', os.environ.get('FORCE_HTTPS')
)
SECURE_SSL_REDIRECT = parse_bool(
    _secure_ssl_redirect_value,
    default=False,
    name='DJANGO_SECURE_SSL_REDIRECT',
)
if parse_bool(
    os.environ.get('DJANGO_TRUST_X_FORWARDED_PROTO'),
    default=False,
    name='DJANGO_TRUST_X_FORWARDED_PROTO',
):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG and parse_bool(
    os.environ.get('DJANGO_ENABLE_HSTS'),
    default=False,
    name='DJANGO_ENABLE_HSTS',
):
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = parse_bool(
        os.environ.get('DJANGO_HSTS_INCLUDE_SUBDOMAINS'),
        default=False,
        name='DJANGO_HSTS_INCLUDE_SUBDOMAINS',
    )
    SECURE_HSTS_PRELOAD = parse_bool(
        os.environ.get('DJANGO_HSTS_PRELOAD'),
        default=False,
        name='DJANGO_HSTS_PRELOAD',
    )

# Custom setting for SSO callback URL construction.
SSO_FORCE_HTTPS = parse_bool(
    os.environ.get('SSO_FORCE_HTTPS'),
    default=not DEBUG,
    name='SSO_FORCE_HTTPS',
)
