# Generated by Django 5.1.2 on 2025-08-13 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSOProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for the SSO provider', max_length=100, unique=True)),
                ('protocol', models.CharField(choices=[('saml', 'SAML 2.0'), ('oidc', 'OpenID Connect')], help_text='SSO Protocol type', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('testing', 'Testing')], default='inactive', help_text='Provider status', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('enabled', models.BooleanField(default=False, help_text='Enable/disable this provider for authentication')),
                ('allow_registration', models.BooleanField(default=True, help_text='Allow automatic user registration')),
                ('debug_mode', models.BooleanField(default=False, help_text='Enable debug logging')),
                ('saml_idp_entity_id', models.URLField(blank=True, max_length=500, null=True, verbose_name='SAML IdP Entity ID')),
                ('saml_idp_sso_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='SAML IdP Single Sign-On URL')),
                ('saml_idp_slo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='SAML IdP Single Logout URL')),
                ('saml_idp_x509cert', models.TextField(blank=True, null=True, verbose_name='SAML IdP x509 Certificate')),
                ('saml_sp_entity_id', models.URLField(blank=True, max_length=500, null=True, verbose_name='SAML SP Entity ID')),
                ('saml_sp_acs_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='SAML SP ACS URL')),
                ('saml_sp_slo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='SAML SP SLO URL')),
                ('saml_sp_x509cert', models.TextField(blank=True, null=True, verbose_name='SAML SP x509 Certificate')),
                ('saml_sp_private_key', models.TextField(blank=True, null=True, verbose_name='SAML SP Private Key')),
                ('saml_name_id_format', models.CharField(blank=True, default='urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress', max_length=255, verbose_name='SAML NameID Format')),
                ('saml_want_messages_signed', models.BooleanField(default=True)),
                ('saml_want_assertions_signed', models.BooleanField(default=False)),
                ('saml_authn_requests_signed', models.BooleanField(default=True)),
                ('saml_logout_requests_signed', models.BooleanField(default=True)),
                ('saml_logout_responses_signed', models.BooleanField(default=True)),
                ('saml_signature_algorithm', models.CharField(default='http://www.w3.org/2001/04/xmldsig-more#rsa-sha256', max_length=255)),
                ('saml_digest_algorithm', models.CharField(default='http://www.w3.org/2001/04/xmlenc#sha256', max_length=255)),
                ('saml_strict_mode', models.BooleanField(default=True)),
                ('oidc_client_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='OIDC Client ID')),
                ('oidc_client_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='OIDC Client Secret')),
                ('oidc_discovery_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='OIDC Discovery URL')),
                ('oidc_authorization_endpoint', models.URLField(blank=True, max_length=500, null=True, verbose_name='OIDC Authorization Endpoint')),
                ('oidc_token_endpoint', models.URLField(blank=True, max_length=500, null=True, verbose_name='OIDC Token Endpoint')),
                ('oidc_userinfo_endpoint', models.URLField(blank=True, max_length=500, null=True, verbose_name='OIDC UserInfo Endpoint')),
                ('oidc_jwks_uri', models.URLField(blank=True, max_length=500, null=True, verbose_name='OIDC JWKS URI')),
                ('oidc_issuer', models.URLField(blank=True, max_length=500, null=True, verbose_name='OIDC Issuer')),
                ('oidc_scopes', models.CharField(blank=True, default='openid email profile', max_length=255, verbose_name='OIDC Scopes')),
                ('attr_email', models.CharField(default='email', max_length=100, verbose_name='Email Attribute')),
                ('attr_first_name', models.CharField(default='first_name', max_length=100, verbose_name='First Name Attribute')),
                ('attr_last_name', models.CharField(default='last_name', max_length=100, verbose_name='Last Name Attribute')),
                ('attr_username', models.CharField(default='email', max_length=100, verbose_name='Username Attribute')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('test_results', models.JSONField(blank=True, default=dict, help_text='Test results and logs')),
            ],
            options={
                'verbose_name': 'SSO Provider',
                'verbose_name_plural': 'SSO Providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SSOAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_attempt', 'Login Attempt'), ('login_success', 'Login Success'), ('login_failure', 'Login Failure'), ('logout', 'Logout'), ('test_connection', 'Test Connection'), ('config_change', 'Configuration Change')], max_length=20)),
                ('user_identifier', models.CharField(blank=True, help_text='Username or email', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='sso_auth.ssoprovider')),
            ],
            options={
                'verbose_name': 'SSO Audit Log',
                'verbose_name_plural': 'SSO Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
