# Generated by Django 5.1.2 on 2025-08-20 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso_auth', '0002_add_sso_user_profile'),
        ('sso_auth', '0002_migrate_saml_config'),
    ]

    operations = [
    ]
