# Generated by Django 5.1.2 on 2025-08-20 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso_auth', '0003_merge_20250820_2213'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssouserprofile',
            name='provider',
            field=models.ForeignKey(help_text='SSO provider used to authenticate this user', on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='sso_auth.ssoprovider'),
        ),
        migrations.AlterField(
            model_name='ssouserprofile',
            name='raw_attributes',
            field=models.JSONField(default=dict, help_text='All raw SSO attributes received from provider'),
        ),
        migrations.AlterField(
            model_name='ssouserprofile',
            name='user',
            field=models.OneToOneField(help_text='Associated Django user', on_delete=django.db.models.deletion.CASCADE, related_name='sso_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='ssouserprofile',
            unique_together={('user', 'provider')},
        ),
    ]
