# Generated by Django 5.1.2 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso_auth', '0004_alter_ssouserprofile_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssoprovider',
            name='oidc_client_secret',
            field=models.TextField(blank=True, null=True, verbose_name='OIDC Client Secret'),
        ),
    ]
