# Generated by Django 5.1.2 on 2026-08-13

from cryptography.fernet import Fernet, InvalidToken
from django.conf import settings
from django.db import migrations


ENCRYPTED_SSO_SECRET_PREFIX = 'enc:v1:'
SECRET_FIELD_NAMES = ('oidc_client_secret', 'saml_sp_private_key')


def _fernet():
    try:
        return Fernet(settings.ENCRYPTION_KEY.encode())
    except (AttributeError, TypeError, ValueError) as exc:
        raise RuntimeError('SSO secret encryption configuration is invalid.') from exc


def _encrypt_existing_value(cipher, provider_id, field_name, value):
    if not isinstance(value, str):
        raise RuntimeError(f'SSOProvider {provider_id} has an invalid {field_name} value.')
    if value.startswith('enc:'):
        if not value.startswith(ENCRYPTED_SSO_SECRET_PREFIX):
            raise RuntimeError(f'SSOProvider {provider_id} has an unsupported {field_name} encryption version.')
        try:
            cipher.decrypt(value[len(ENCRYPTED_SSO_SECRET_PREFIX):].encode())
        except (InvalidToken, UnicodeError, ValueError) as exc:
            raise RuntimeError(f'SSOProvider {provider_id} has an invalid encrypted {field_name}.') from exc
        return value
    try:
        return ENCRYPTED_SSO_SECRET_PREFIX + cipher.encrypt(value.encode()).decode()
    except (UnicodeError, ValueError) as exc:
        raise RuntimeError(f'SSOProvider {provider_id} {field_name} encryption failed.') from exc


def encrypt_ssoprovider_secrets(apps, schema_editor):
    SSOProvider = apps.get_model('sso_auth', 'SSOProvider')
    cipher = _fernet()
    for provider in SSOProvider.objects.iterator():
        update_fields = []
        for field_name in SECRET_FIELD_NAMES:
            value = getattr(provider, field_name)
            if value in (None, ''):
                continue
            encrypted_value = _encrypt_existing_value(cipher, provider.pk, field_name, value)
            if encrypted_value != value:
                setattr(provider, field_name, encrypted_value)
                update_fields.append(field_name)
        if update_fields:
            provider.save(update_fields=update_fields)


class Migration(migrations.Migration):

    atomic = True

    dependencies = [
        ('sso_auth', '0005_alter_ssoprovider_oidc_client_secret'),
    ]

    operations = [
        migrations.RunPython(encrypt_ssoprovider_secrets, migrations.RunPython.noop),
    ]
