# Generated by Django 5.1.2 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso_auth', '0006_encrypt_ssoprovider_secrets'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ssouserprofile',
            constraint=models.UniqueConstraint(
                fields=('provider', 'sso_id'),
                name='sso_auth_provider_sso_id_uniq',
            ),
        ),
    ]
