# Generated by Django 5.1.2 on 2026-08-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso_auth', '0007_ssouserprofile_sso_auth_provider_sso_id_uniq'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAMLReplayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assertion_id_hash', models.CharField(max_length=64)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saml_replay_records', to='sso_auth.ssoprovider')),
            ],
        ),
        migrations.AddConstraint(
            model_name='samlreplayrecord',
            constraint=models.UniqueConstraint(fields=('provider', 'assertion_id_hash'), name='sso_auth_replay_provider_assertion_uniq'),
        ),
    ]
