# Generated by Django 5.1.2 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso_auth', '0008_samlreplayrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssoprovider',
            name='saml_identity_policy',
            field=models.CharField(
                choices=[
                    ('disabled', 'Disabled — do not allow SAML account identity'),
                    ('persistent_nameid', 'Persistent NameID — require SAML persistent NameID format'),
                ],
                default='disabled',
                help_text='Controls which received SAML identity may be trusted; separate from the SP-requested NameID format.',
                max_length=32,
                verbose_name='SAML Identity Policy',
            ),
        ),
    ]
