# Generated by Django 5.1.2 on 2026-08-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso_auth', '0009_ssoprovider_saml_identity_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssoprovider',
            name='saml_idp_sso_binding',
            field=models.CharField(choices=[('http_redirect', 'HTTP-Redirect'), ('http_post', 'HTTP-POST')], default='http_redirect', help_text='SingleSignOnService binding the AuthnRequest is sent with.', max_length=16, verbose_name='SAML IdP SSO Binding'),
        ),
        migrations.AddField(
            model_name='ssoprovider',
            name='saml_idp_x509cert_additional',
            field=models.TextField(blank=True, help_text='Optional rollover signing certificate(s). Paste one or more PEM certificates.', null=True, verbose_name='SAML IdP Additional x509 Certificates'),
        ),
        migrations.AddField(
            model_name='ssoprovider',
            name='saml_immutable_attribute_name',
            field=models.CharField(blank=True, help_text='Required when SAML Identity Policy is "Configured immutable attribute". Exact assertion attribute name the IdP issues as a stable, unique subject identifier (for example an object GUID or employee ID). Never use email, username, or display name here.', max_length=255, verbose_name='SAML Immutable Attribute Name'),
        ),
        migrations.AlterField(
            model_name='ssoprovider',
            name='saml_identity_policy',
            field=models.CharField(choices=[('disabled', 'Disabled — do not allow SAML account identity'), ('persistent_nameid', 'Persistent NameID — require SAML persistent NameID format'), ('configured_immutable_attribute', 'Configured immutable attribute — require a named, non-empty assertion attribute')], default='disabled', help_text='Controls which received SAML identity may be trusted; separate from the SP-requested NameID format.', max_length=32, verbose_name='SAML Identity Policy'),
        ),
    ]
