# Generated by Django 5.1.2 on 2025-06-12 08:46

import django.db.models.deletion
import django.utils.timezone
import timezone_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='company_logos/')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='company_favicons/')),
                ('show_logo_as_text', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French')], default='en', max_length=10)),
                ('timezone', timezone_field.fields.TimeZoneField(default='UTC')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36, unique=True)),
                ('formname', models.CharField(blank=True, max_length=255, null=True)),
                ('form_description', models.CharField(blank=True, max_length=255, null=True)),
                ('config', models.TextField(default='{}')),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('authenticated', 'Authenticated Users'), ('selected_users', 'Specific Users')], default='public', max_length=20)),
                ('login_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'dynamicform',
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='integration_icons/')),
                ('description', models.TextField()),
                ('fields', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'integration',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_heading', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('restricted_to', models.CharField(choices=[('all', 'All Users'), ('active', 'Active Users'), ('staff', 'Staff Users'), ('superuser', 'Superusers')], default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'db_table': 'menu',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('connection_type', models.CharField(choices=[('mssql', 'Microsoft SQL Server'), ('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('oracle', 'Oracle')], max_length=20)),
                ('server', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=10)),
                ('database_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'databaseconnection',
                'ordering': ['-is_default', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(max_length=100)),
                ('source_timestamp', models.DateTimeField()),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrator.client')),
            ],
            options={
                'db_table': 'datarecord',
            },
        ),
        migrations.CreateModel(
            name='FormPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='integrator.dynamicform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'formpermission',
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissionID', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('submission_data', models.JSONField()),
                ('response', models.JSONField(blank=True, default=dict)),
                ('form_uuid', models.CharField(blank=True, max_length=36, null=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrator.dynamicform')),
            ],
            options={
                'db_table': 'formsubmission',
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='integrator.formsubmission')),
            ],
            options={
                'db_table': 'fileupload',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('named_url', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_external', models.BooleanField(default=False)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('restricted_to', models.CharField(choices=[('all', 'All Users'), ('active', 'Active Users'), ('staff', 'Staff Users'), ('superuser', 'Superusers')], default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='integrator.menu')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'db_table': 'menuitem',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', models.JSONField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrator.integration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'integrationcredential',
                'unique_together': {('user', 'integration')},
            },
        ),
        migrations.CreateModel(
            name='SavedProcedureExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('procedure_name', models.CharField(max_length=100)),
                ('procedure_schema', models.CharField(blank=True, max_length=100, null=True)),
                ('parameters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_executions', to='integrator.databaseconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_procedure_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'savedprocedureexecution',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('query_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='integrator.databaseconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'savedquery',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
