# Generated by Django 5.1.2 on 2025-06-12 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicform',
            name='login_required',
        ),
    ]
