# Generated by Django 5.1.2 on 2025-06-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0002_remove_dynamicform_login_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicform',
            name='login_required',
            field=models.BooleanField(default=True),
        ),
    ]
