# Generated by Django 5.1.2 on 2025-08-10 19:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0003_dynamicform_login_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicform',
            name='custom_colors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='custom_logo',
            field=models.ImageField(blank=True, null=True, upload_to='form_logos/'),
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='footer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='header_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='template_type',
            field=models.CharField(choices=[('default', 'Default Template'), ('corporate', 'Corporate Template'), ('minimal', 'Minimal Template'), ('modern', 'Modern Template'), ('classic', 'Classic Template'), ('branded', 'Branded Template')], default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='dynamicform',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
