# Generated by Django 5.1.2 on 2025-08-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0004_dynamicform_custom_colors_dynamicform_custom_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicform',
            name='sidebar_section1_content',
            field=models.TextField(blank=True, default='Please fill out all required fields marked with an asterisk (*) to complete your submission.'),
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='sidebar_section1_title',
            field=models.CharField(blank=True, default='Information', max_length=100),
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='sidebar_section2_content',
            field=models.TextField(blank=True, default='If you need assistance completing this form, please contact our support team.'),
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='sidebar_section2_title',
            field=models.CharField(blank=True, default='Contact', max_length=100),
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='sidebar_section3_content',
            field=models.TextField(blank=True, default='Your information is secure and will only be used for the purposes stated in our privacy policy.'),
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='sidebar_section3_title',
            field=models.CharField(blank=True, default='Privacy', max_length=100),
        ),
    ]
