# Generated by Django 5.1.2 on 2025-08-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0005_dynamicform_sidebar_section1_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicform',
            name='enable_redirect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='success_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
