# Generated by Django 5.1.2 on 2025-08-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0006_dynamicform_enable_redirect_dynamicform_redirect_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicform',
            name='enable_sso_prepopulate',
            field=models.BooleanField(default=False, help_text='Enable SSO field prepopulation'),
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='sso_disabled_fields',
            field=models.JSONField(blank=True, default=list, help_text='List of field names that should be disabled for SSO users'),
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='sso_prepopulate_fields',
            field=models.JSONField(blank=True, default=dict, help_text='JSON mapping of form fields to SSO attributes'),
        ),
    ]
