# Generated by Django 5.1.2 on 2025-08-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0007_dynamicform_enable_sso_prepopulate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicform',
            name='auto_redirect_to_sso',
            field=models.BooleanField(default=True, help_text='Automatically redirect to SSO login instead of showing login page'),
        ),
    ]
