# Generated by Django 5.1.2 on 2025-08-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0008_dynamicform_auto_redirect_to_sso'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicform',
            name='dynamic_options_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration for dynamic dropdown/radio/checkbox options'),
        ),
    ]
