# Generated by Django 5.1.2 on 2026-08-13 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0009_add_dynamic_options_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
