# Generated by Django 5.1.2 on 2026-08-13 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0010_remove_menuitem_parent_delete_menu_delete_menuitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(choices=[('mssql', 'Microsoft SQL Server'), ('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('oracle', 'Oracle')], max_length=20)),
                ('database_name', models.CharField(max_length=100)),
                ('schema', models.CharField(max_length=100)),
                ('procedure_name', models.CharField(max_length=100)),
                ('signature', models.CharField(blank=True, default='', max_length=255)),
                ('behavior', models.CharField(choices=[('READ_EXPECTED', 'Read expected'), ('MUTATING', 'Mutating')], max_length=20)),
                ('enabled', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_procedures', to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_procedures', to='integrator.databaseconnection')),
            ],
            options={
                'db_table': 'approvedprocedure',
            },
        ),
        migrations.CreateModel(
            name='ApprovedProcedureParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=128)),
                ('direction', models.CharField(choices=[('IN', 'Input'), ('OUT', 'Output'), ('INOUT', 'Input/output')], default='IN', max_length=5)),
                ('database_type', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=True)),
                ('nullable', models.BooleanField(default=False)),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
                ('approved_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='integrator.approvedprocedure')),
            ],
            options={
                'db_table': 'approvedprocedureparameter',
                'ordering': ['ordinal'],
            },
        ),
        migrations.AddConstraint(
            model_name='approvedprocedure',
            constraint=models.UniqueConstraint(fields=('connection', 'schema', 'procedure_name', 'signature'), name='unique_approved_procedure_identity'),
        ),
        migrations.AddConstraint(
            model_name='approvedprocedureparameter',
            constraint=models.UniqueConstraint(fields=('approved_procedure', 'ordinal'), name='unique_approved_procedure_parameter_ordinal'),
        ),
        migrations.AddConstraint(
            model_name='approvedprocedureparameter',
            constraint=models.UniqueConstraint(fields=('approved_procedure', 'name'), name='unique_approved_procedure_parameter_name'),
        ),
    ]
