# Generated by Django 5.1.2 on 2026-08-13 11:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0011_approvedprocedure_approvedprocedureparameter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureExecutionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('failure_category', models.CharField(choices=[('SUCCESS', 'Success'), ('VALIDATION_FAILED', 'Validation failed'), ('APPROVAL_DISABLED', 'Approval disabled'), ('MUTATING_DENIED', 'Mutating procedure denied'), ('IDENTITY_MISMATCH', 'Approval identity mismatch'), ('READONLY_SETUP_FAILED', 'Read-only setup failed'), ('CONNECTION_FAILED', 'Connection failed'), ('TIMEOUT', 'Timeout'), ('EXECUTION_FAILED', 'Execution failed'), ('RESULT_PROCESSING_FAILED', 'Result processing failed')], max_length=32)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('result_set_count', models.PositiveIntegerField(default=0)),
                ('truncated', models.BooleanField(default=False)),
                ('engine_snapshot', models.CharField(max_length=20)),
                ('database_name_snapshot', models.CharField(max_length=100)),
                ('schema_snapshot', models.CharField(max_length=100)),
                ('procedure_name_snapshot', models.CharField(max_length=100)),
                ('approved_procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_audits', to='integrator.approvedprocedure')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedure_execution_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procedureexecutionaudit',
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['user', 'started_at'], name='procedureex_user_id_62e468_idx'), models.Index(fields=['approved_procedure', 'started_at'], name='procedureex_approve_9c689f_idx')],
            },
        ),
    ]
